### PR TITLE
Allow public read access for uploaded files

### PR DESCRIPTION
**Pull request by pushrax**
@camilo mentioned there was an issue with uploaded files not being readable, I assume this is what he meant.

r/ @boourns @fbogsany @camilo

### CODE REVIEW

**Comment by camilo** [comment]
ping @pushrax why haven't we merged this?

**Comment by pushrax** [comment]
Was pending perf testing, and as expected it's really damn slow. Takes quite a bit longer than 24hrs to run now (the run I started yesterday morning is still going). Not sure how we want to handle that, however we can merge this as a start.

**Comment by aybabtme** [comment]
@pushmatrix runs should be in a <10 hours usually as its supposed to do only the diff from last day. check if it's using the diffs properly or if its using an old one

**Comment by pushrax** [comment]
@aybabtme it is fetching acls for new files now which adds some time. In addition, the bucket size is growing fast - almost 80M keys now. Just fetching keys takes several hours.

**Comment by aybabtme** [comment]
:cloud: scale!

**Pull request merged**
